from enum import StrEnum, auto


class BookingDurables(StrEnum):
    SESSION_SVC_TICKETS_CREATED_BOOKING_CREATE = auto()
    SESSION_SVC_TICKETS_BULK_CREATED_BOOKINGS_CREATE = auto()
    SESSION_SVC_TICKETS_UPDATED_BOOKING_SYNC = auto()
    SESSION_SVC_TICKETS_BULK_UPDATED_BOOKINGS_SYNC = auto()
    SESSION_SVC_TICKET_DELETED_BOOKING_DELETE = auto()
