from enum import StrEnum, auto


class HallDurables(StrEnum):
    SESSION_SVC_SEATS_CREATED_HALL_RECALCULATE = auto()
    SESSION_SVC_SEATS_BULK_CREATED_HALL_RECALCULATE = auto()
    SESSION_SVC_SEATS_DELETED_HALL_RECALCULATE = auto()
